version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    open-pull-requests-limit: 10
    reviewers:
      - shgysk8zer0
    assignees:
      - shgysk8zer0
    labels:
      - dependencies
      - javascript
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    open-pull-requests-limit: 10
    reviewers:
      - shgysk8zer0
    assignees:
      - shgysk8zer0
    labels:
      - dependencies
      - github-actions
