version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: '09:00'
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
    assignees:
      - shgysk8zer0
    labels:
      - dependencies
      - javascript
    groups:
      all-dependencies:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: '09:00'
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
    assignees:
      - shgysk8zer0
    labels:
      - dependencies
      - github-actions
    groups:
      all-dependencies:
        patterns:
          - '*'
